/**
 * Instructor → Course Mapping & Lesson Stubs
 *
 * 50 lesson stubs mapped to the 10 named instructors.
 * Each lesson has title, slug, summary, objectives, difficulty, time,
 * instructor, lab connection, project connection, and reflection prompt.
 */

export interface LessonStub {
  readonly title: string;
  readonly slug: string;
  readonly summary: string;
  readonly learningObjectives: readonly string[];
  readonly difficulty: "beginner" | "intermediate" | "advanced";
  readonly estimatedMinutes: number;
  readonly instructorId: string;
  readonly trackSlug: string;
  readonly order: number;
  readonly labConnection: string;
  readonly projectConnection: string;
  readonly reflectionPrompt: string;
}

// ─── JEFF SPICOLI — 5 lessons ───────────────────────────────────

const spicoli: LessonStub[] = [
  {
    title: "What AI Actually Is",
    slug: "what-ai-actually-is",
    summary: "Strip away the hype and understand what AI really does — pattern matching, prediction, and generation — explained with zero jargon.",
    learningObjectives: ["Define AI in plain language", "Distinguish AI from automation", "Identify 3 things AI does well and 3 it doesn't"],
    difficulty: "beginner",
    estimatedMinutes: 15,
    instructorId: "spicoli",
    trackSlug: "ai-foundations",
    order: 1,
    labConnection: "Prompt Lab — try asking an AI to explain itself",
    projectConnection: "Write your own 'AI in 60 seconds' explainer",
    reflectionPrompt: "Before today, what did you think AI was? How has that changed?",
  },
  {
    title: "Talking to AI Without Overthinking It",
    slug: "talking-to-ai-without-overthinking",
    summary: "Your first prompts don't need to be perfect. Learn the 'just ask' method and iterate from there.",
    learningObjectives: ["Write a basic prompt", "Understand prompt → response flow", "Practice 3 prompt variations"],
    difficulty: "beginner",
    estimatedMinutes: 20,
    instructorId: "spicoli",
    trackSlug: "prompt-engineering",
    order: 1,
    labConnection: "Prompt Lab — write 5 prompts, compare results",
    projectConnection: "Create a prompt journal with your best attempts",
    reflectionPrompt: "What was the weirdest thing AI said back to you today? Why do you think it said that?",
  },
  {
    title: "First Prompts That Actually Work",
    slug: "first-prompts-that-work",
    summary: "Learn the Role-Task-Context-Format framework so your prompts get useful results on the first try.",
    learningObjectives: ["Apply the RTCF framework", "Compare vague vs. structured prompts", "Generate 3 useful outputs"],
    difficulty: "beginner",
    estimatedMinutes: 25,
    instructorId: "spicoli",
    trackSlug: "prompt-engineering",
    order: 2,
    labConnection: "Prompt Lab — A/B test structured vs. unstructured prompts",
    projectConnection: "Build a 'Prompt Recipe Card' for a task you do weekly",
    reflectionPrompt: "Which part of the framework made the biggest difference in your results?",
  },
  {
    title: "Creativity with AI",
    slug: "creativity-with-ai",
    summary: "Use AI as a brainstorming partner for stories, art ideas, music concepts, and creative projects.",
    learningObjectives: ["Use AI for creative ideation", "Generate 10 ideas in 5 minutes", "Evaluate which ideas have potential"],
    difficulty: "beginner",
    estimatedMinutes: 25,
    instructorId: "spicoli",
    trackSlug: "creative-ai",
    order: 1,
    labConnection: "Prompt Lab — creative generation session",
    projectConnection: "Create a 'Creative AI Sketchbook' with 20 generated concepts",
    reflectionPrompt: "Did AI help you think of something you never would have on your own?",
  },
  {
    title: "AI for Everyday Life",
    slug: "ai-for-everyday-life",
    summary: "Practical ways to use AI right now — homework help, planning, writing, creative projects, and more.",
    learningObjectives: ["Identify 5 daily AI use cases", "Set up an AI assistant workflow", "Know when NOT to use AI"],
    difficulty: "beginner",
    estimatedMinutes: 20,
    instructorId: "spicoli",
    trackSlug: "ai-foundations",
    order: 2,
    labConnection: "Prompt Lab — build a personal AI workflow",
    projectConnection: "Document your 'AI Day' — track every time AI could help",
    reflectionPrompt: "What's one thing you'll start using AI for this week?",
  },
];

// ─── MR. MIYAGI — 5 lessons ────────────────────────────────────

const miyagi: LessonStub[] = [
  {
    title: "Foundations of Intelligence Systems",
    slug: "foundations-intelligence-systems",
    summary: "Understand the building blocks: data, models, training, inference. No shortcuts.",
    learningObjectives: ["Define data, model, training, and inference", "Trace how a prediction flows through a model", "Identify 3 failure points"],
    difficulty: "beginner",
    estimatedMinutes: 30,
    instructorId: "miyagi",
    trackSlug: "ai-foundations",
    order: 3,
    labConnection: "Prompt Lab — probe a model's confidence levels",
    projectConnection: "Create a systems diagram of how an AI model works",
    reflectionPrompt: "What surprised you most about how models actually work?",
  },
  {
    title: "Why Models Fail",
    slug: "why-models-fail",
    summary: "Every model has failure modes. Learn to anticipate them, test for them, and design around them.",
    learningObjectives: ["List 5 common failure modes", "Test a model for hallucination", "Design a simple evaluation check"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "miyagi",
    trackSlug: "ai-foundations",
    order: 4,
    labConnection: "Prompt Lab — deliberately trigger failure modes",
    projectConnection: "Write a 'Failure Field Guide' for one AI tool you use",
    reflectionPrompt: "Have you ever trusted an AI answer that turned out wrong? What would you do differently?",
  },
  {
    title: "Evaluation and Discipline",
    slug: "evaluation-and-discipline",
    summary: "How to measure whether AI output is actually good — not just plausible.",
    learningObjectives: ["Define evaluation criteria", "Score AI outputs on accuracy and relevance", "Build a simple rubric"],
    difficulty: "intermediate",
    estimatedMinutes: 35,
    instructorId: "miyagi",
    trackSlug: "ai-foundations",
    order: 5,
    labConnection: "Prompt Lab — evaluate 10 outputs with a rubric",
    projectConnection: "Create an evaluation template for your team or class",
    reflectionPrompt: "How do you know when an AI answer is 'good enough' vs. when you need to dig deeper?",
  },
  {
    title: "Truth vs Confidence in AI",
    slug: "truth-vs-confidence",
    summary: "AI sounds confident even when it's wrong. Learn to distinguish signal from noise.",
    learningObjectives: ["Identify calibration problems", "Test AI confidence vs. accuracy", "Develop a skepticism framework"],
    difficulty: "intermediate",
    estimatedMinutes: 25,
    instructorId: "miyagi",
    trackSlug: "ai-foundations",
    order: 6,
    labConnection: "Prompt Lab — ask the same question 5 ways, compare confidence",
    projectConnection: "Write a 'Confidence Calibration Report' on one AI tool",
    reflectionPrompt: "When does confidence become dangerous?",
  },
  {
    title: "Practice Routines for Mastery",
    slug: "practice-routines-mastery",
    summary: "Deliberate practice for AI literacy — daily exercises, reflection habits, and progression paths.",
    learningObjectives: ["Design a 7-day practice routine", "Track skill progression", "Identify personal learning gaps"],
    difficulty: "beginner",
    estimatedMinutes: 20,
    instructorId: "miyagi",
    trackSlug: "ai-foundations",
    order: 7,
    labConnection: "All Labs — rotational practice schedule",
    projectConnection: "Create your personal Ridgemont AI Practice Plan",
    reflectionPrompt: "What skill do you want to master first, and what will you practice daily?",
  },
];

// ─── BRIAN JOHNSON — 5 lessons ──────────────────────────────────

const brian: LessonStub[] = [
  {
    title: "Research with AI",
    slug: "research-with-ai",
    summary: "How to use AI as a research assistant without falling for hallucinated sources.",
    learningObjectives: ["Formulate research queries", "Cross-reference AI sources", "Build a source verification workflow"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "brian",
    trackSlug: "rag-search",
    order: 1,
    labConnection: "RAG Lab — search real documents and verify results",
    projectConnection: "Complete a mini-research paper with verified AI-assisted sources",
    reflectionPrompt: "How is researching with AI different from using a search engine?",
  },
  {
    title: "RAG Fundamentals",
    slug: "rag-fundamentals",
    summary: "Retrieval Augmented Generation explained — how AI can search real documents and cite real sources.",
    learningObjectives: ["Explain the RAG pipeline", "Distinguish generation from retrieval", "Run a basic RAG query"],
    difficulty: "intermediate",
    estimatedMinutes: 35,
    instructorId: "brian",
    trackSlug: "rag-search",
    order: 2,
    labConnection: "RAG Lab — run your first retrieval pipeline",
    projectConnection: "Build a personal knowledge base with RAG",
    reflectionPrompt: "Why does giving AI access to real documents produce better answers?",
  },
  {
    title: "Citation Chains — Trusting What You Read",
    slug: "citation-chains",
    summary: "Follow the evidence trail — from AI claim to source document to original research.",
    learningObjectives: ["Trace a claim back 3 levels", "Evaluate source quality", "Build a citation map"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "brian",
    trackSlug: "rag-search",
    order: 3,
    labConnection: "RAG Lab — citation tracing exercise",
    projectConnection: "Audit 5 AI-generated claims and trace each to its source",
    reflectionPrompt: "Have you ever seen a 'source' that turned out to be fabricated? How would you catch it?",
  },
  {
    title: "Source Credibility in the AI Era",
    slug: "source-credibility",
    summary: "Not all sources are equal. Learn frameworks for evaluating reliability, bias, and authority.",
    learningObjectives: ["Apply the CRAAP test to AI sources", "Identify bias indicators", "Rank sources by reliability"],
    difficulty: "intermediate",
    estimatedMinutes: 25,
    instructorId: "brian",
    trackSlug: "rag-search",
    order: 4,
    labConnection: "RAG Lab — source credibility scoring exercise",
    projectConnection: "Create a personal 'Trusted Sources' directory",
    reflectionPrompt: "What makes a source trustworthy? Can AI itself be a credible source?",
  },
  {
    title: "Building Knowledge Workflows",
    slug: "building-knowledge-workflows",
    summary: "Design systems that capture, organize, and retrieve knowledge using AI-powered tools.",
    learningObjectives: ["Design a knowledge capture workflow", "Connect ingestion to retrieval", "Build a personal knowledge system"],
    difficulty: "advanced",
    estimatedMinutes: 40,
    instructorId: "brian",
    trackSlug: "rag-search",
    order: 5,
    labConnection: "RAG Lab — build an end-to-end knowledge pipeline",
    projectConnection: "Deploy a personal knowledge base that you actually use",
    reflectionPrompt: "What knowledge do you access most often? How could AI help you organize it?",
  },
];

// ─── DWAYNE WAYNE — 5 lessons ───────────────────────────────────

const dwayne: LessonStub[] = [
  {
    title: "APIs and Tool Calling",
    slug: "apis-and-tool-calling",
    summary: "How AI connects to external tools — APIs, function calling, and structured outputs.",
    learningObjectives: ["Explain what an API is", "Make a basic API call", "Understand function calling in LLMs"],
    difficulty: "intermediate",
    estimatedMinutes: 35,
    instructorId: "dwayne",
    trackSlug: "mcp-tools",
    order: 1,
    labConnection: "MCP Lab — call a real tool through AI",
    projectConnection: "Build a simple API wrapper for an AI model",
    reflectionPrompt: "What's the difference between an AI that thinks and an AI that does?",
  },
  {
    title: "MCP Fundamentals — Connecting AI to Tools",
    slug: "mcp-fundamentals",
    summary: "Model Context Protocol explained — the standard for giving AI access to structured tools and data.",
    learningObjectives: ["Explain MCP architecture", "List MCP tool categories", "Configure a basic MCP server"],
    difficulty: "intermediate",
    estimatedMinutes: 40,
    instructorId: "dwayne",
    trackSlug: "mcp-tools",
    order: 2,
    labConnection: "MCP Lab — connect and test MCP tools",
    projectConnection: "Set up a local MCP server with 3 tools",
    reflectionPrompt: "Why does standardizing tool access matter for AI? What happens without standards?",
  },
  {
    title: "Agent Design from Scratch",
    slug: "agent-design-from-scratch",
    summary: "Build an AI agent that plans, reasons, and acts — not just a chatbot that responds.",
    learningObjectives: ["Define an AI agent", "Design a plan-act-observe loop", "Build a basic agent scaffold"],
    difficulty: "intermediate",
    estimatedMinutes: 45,
    instructorId: "dwayne",
    trackSlug: "agent-frameworks",
    order: 1,
    labConnection: "Agent Lab — build and run your first agent",
    projectConnection: "Deploy a working agent that completes a real task",
    reflectionPrompt: "What makes an agent different from a chatbot? When would you choose one over the other?",
  },
  {
    title: "Build Your First AI Workflow",
    slug: "build-first-ai-workflow",
    summary: "Chain prompts, tools, and logic into a workflow that runs end-to-end without manual steps.",
    learningObjectives: ["Design a multi-step workflow", "Connect prompt output to tool input", "Handle errors gracefully"],
    difficulty: "intermediate",
    estimatedMinutes: 40,
    instructorId: "dwayne",
    trackSlug: "agent-frameworks",
    order: 2,
    labConnection: "Agent Lab + Code Lab — wire a complete pipeline",
    projectConnection: "Ship a workflow that automates something you do manually",
    reflectionPrompt: "What repetitive task would you automate first with AI?",
  },
  {
    title: "Lab-to-Deployment Track",
    slug: "lab-to-deployment",
    summary: "Take your lab project from prototype to production — testing, hardening, and shipping.",
    learningObjectives: ["Write tests for AI workflows", "Handle edge cases", "Deploy to a real environment"],
    difficulty: "advanced",
    estimatedMinutes: 50,
    instructorId: "dwayne",
    trackSlug: "agent-frameworks",
    order: 3,
    labConnection: "Code Lab — full deployment exercise",
    projectConnection: "Graduate project: ship a production-ready AI tool",
    reflectionPrompt: "What's the scariest part of shipping something real? How do you manage that risk?",
  },
];

// ─── FERRIS BUELLER — 5 lessons ─────────────────────────────────

const ferris: LessonStub[] = [
  {
    title: "AI for Side Hustles",
    slug: "ai-for-side-hustles",
    summary: "How to use AI to launch a small project, validate an idea, and ship something people actually want.",
    learningObjectives: ["Identify a real problem to solve", "Use AI to validate demand", "Build an MVP in 1 hour"],
    difficulty: "beginner",
    estimatedMinutes: 30,
    instructorId: "ferris",
    trackSlug: "ai-business",
    order: 1,
    labConnection: "Project Studio — build and launch a micro-product",
    projectConnection: "Launch a real side project using AI tools",
    reflectionPrompt: "What problem do you care enough about to solve? Could AI help you solve it faster?",
  },
  {
    title: "Product Demos That Actually Land",
    slug: "product-demos-that-land",
    summary: "How to present your work so people get it in 30 seconds — storytelling, structure, and AI-assisted polish.",
    learningObjectives: ["Structure a 2-minute demo", "Use AI for slide/copy generation", "Practice delivering a pitch"],
    difficulty: "beginner",
    estimatedMinutes: 25,
    instructorId: "ferris",
    trackSlug: "ai-business",
    order: 2,
    labConnection: "Project Studio — record and review a product demo",
    projectConnection: "Create a 2-minute video demo of your best project",
    reflectionPrompt: "What's the difference between explaining what something does and showing why it matters?",
  },
  {
    title: "Faster Workflows with AI",
    slug: "faster-workflows-ai",
    summary: "Audit your daily tasks and identify where AI saves time — then actually build the shortcut.",
    learningObjectives: ["Audit your workflow for AI opportunities", "Build 3 AI-powered shortcuts", "Measure time saved"],
    difficulty: "beginner",
    estimatedMinutes: 25,
    instructorId: "ferris",
    trackSlug: "ai-business",
    order: 3,
    labConnection: "Prompt Lab — create reusable workflow templates",
    projectConnection: "Document and share 3 AI workflows that save you time",
    reflectionPrompt: "Where do you waste the most time? Could AI fix that?",
  },
  {
    title: "AI Presentation Skills",
    slug: "ai-presentation-skills",
    summary: "Use AI to write, design, and rehearse presentations that hold attention and drive decisions.",
    learningObjectives: ["Generate presentation outlines with AI", "Design slides with AI tools", "Practice with AI feedback"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "ferris",
    trackSlug: "ai-business",
    order: 4,
    labConnection: "Prompt Lab — presentation generation session",
    projectConnection: "Deliver a polished AI-assisted presentation to your cohort",
    reflectionPrompt: "How does AI change the way you prepare for important moments?",
  },
  {
    title: "Build and Ship a Small Tool",
    slug: "build-and-ship-small-tool",
    summary: "From idea to live product in one session — scope small, ship fast, learn from users.",
    learningObjectives: ["Scope a 1-day build", "Use AI for code generation", "Deploy and share with real users"],
    difficulty: "intermediate",
    estimatedMinutes: 45,
    instructorId: "ferris",
    trackSlug: "ai-business",
    order: 5,
    labConnection: "Project Studio + Code Lab — full build sprint",
    projectConnection: "Ship a tool and get feedback from 3 real users",
    reflectionPrompt: "What did you learn from shipping that you couldn't learn from planning?",
  },
];

// ─── JOHN BENDER — 5 lessons ────────────────────────────────────

const bender: LessonStub[] = [
  {
    title: "AI Manipulation and Narrative Control",
    slug: "ai-manipulation-narrative",
    summary: "How AI can be used to shape stories, manufacture consent, and control what people believe.",
    learningObjectives: ["Identify 3 manipulation patterns", "Analyze a real case study", "Design detection heuristics"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "bender",
    trackSlug: "ethics-society",
    order: 1,
    labConnection: "Media Lab — analyze AI-generated vs. human-written news",
    projectConnection: "Write a media literacy report on one AI manipulation case",
    reflectionPrompt: "Have you ever been fooled by AI-generated content? How did you find out?",
  },
  {
    title: "Platform Power — Who Really Benefits",
    slug: "platform-power",
    summary: "AI platforms aren't neutral. Examine who controls the tools, the data, and the narratives.",
    learningObjectives: ["Map platform power structures", "Identify data ownership issues", "Question 'free' AI tools"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "bender",
    trackSlug: "ethics-society",
    order: 2,
    labConnection: "Media Lab — platform comparison analysis",
    projectConnection: "Create a 'Platform Power Map' for 3 major AI tools",
    reflectionPrompt: "When a tool is free, what are you actually paying with?",
  },
  {
    title: "Media Literacy in the AI Age",
    slug: "media-literacy-ai-age",
    summary: "Traditional media literacy meets AI — deepfakes, synthetic text, and algorithmic curation.",
    learningObjectives: ["Identify synthetic media", "Evaluate algorithmic curation bias", "Build a personal verification framework"],
    difficulty: "intermediate",
    estimatedMinutes: 25,
    instructorId: "bender",
    trackSlug: "ethics-society",
    order: 3,
    labConnection: "Media Lab — deepfake detection exercise",
    projectConnection: "Create a classroom guide to spotting synthetic content",
    reflectionPrompt: "What's more dangerous — an obvious lie or a plausible-sounding falsehood?",
  },
  {
    title: "Bias and Framing",
    slug: "bias-and-framing",
    summary: "Every dataset has a bias. Every model has a frame. Learn to see what's hidden in the output.",
    learningObjectives: ["Identify 4 types of bias", "Test a model for bias", "Propose mitigation strategies"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "bender",
    trackSlug: "ethics-society",
    order: 4,
    labConnection: "Media Lab — bias detection exercise",
    projectConnection: "Write a 'Bias Report' for one AI tool you use regularly",
    reflectionPrompt: "Is it possible to build an unbiased AI? Should we even try?",
  },
  {
    title: "How Systems Shape Belief",
    slug: "how-systems-shape-belief",
    summary: "From filter bubbles to recommendation engines — how AI architectures silently shape what you think.",
    learningObjectives: ["Explain filter bubbles", "Map a recommendation pipeline", "Design counter-measures"],
    difficulty: "advanced",
    estimatedMinutes: 35,
    instructorId: "bender",
    trackSlug: "ethics-society",
    order: 5,
    labConnection: "Media Lab — recommendation engine analysis",
    projectConnection: "Create an 'Attention Audit' of your own AI-curated feeds",
    reflectionPrompt: "How much of what you believe was chosen for you by an algorithm?",
  },
];

// ─── CLAIRE STANDISH — 5 lessons ────────────────────────────────

const claire: LessonStub[] = [
  {
    title: "High-Quality AI Writing",
    slug: "high-quality-ai-writing",
    summary: "Move beyond 'AI slop' — learn to produce writing with AI that sounds human, specific, and real.",
    learningObjectives: ["Identify generic AI writing patterns", "Apply 5 quality filters", "Produce polished final drafts"],
    difficulty: "beginner",
    estimatedMinutes: 25,
    instructorId: "claire",
    trackSlug: "creative-ai",
    order: 2,
    labConnection: "Prompt Lab — writing refinement session",
    projectConnection: "Submit a portfolio piece written with AI assistance that sounds like you",
    reflectionPrompt: "Can you tell when something was written by AI? What gives it away?",
  },
  {
    title: "Personal Brand with AI",
    slug: "personal-brand-ai",
    summary: "Use AI to define, refine, and express your personal brand across platforms.",
    learningObjectives: ["Define your voice and values", "Generate brand-consistent content", "Build a personal brand kit"],
    difficulty: "beginner",
    estimatedMinutes: 25,
    instructorId: "claire",
    trackSlug: "creative-ai",
    order: 3,
    labConnection: "Prompt Lab — brand voice calibration",
    projectConnection: "Create a personal brand guide powered by AI",
    reflectionPrompt: "What do you want people to think when they see your work?",
  },
  {
    title: "Making Deliverables Look Polished",
    slug: "polished-deliverables",
    summary: "The gap between 'done' and 'impressive' is smaller than you think — AI can close it.",
    learningObjectives: ["Apply formatting best practices", "Use AI for proofreading and layout", "Present work that commands attention"],
    difficulty: "beginner",
    estimatedMinutes: 20,
    instructorId: "claire",
    trackSlug: "creative-ai",
    order: 4,
    labConnection: "Prompt Lab — deliverable polishing workshop",
    projectConnection: "Transform one rough project into a professional-grade deliverable",
    reflectionPrompt: "Does presentation matter as much as substance? When and why?",
  },
  {
    title: "Communicating with Precision",
    slug: "communicating-precision",
    summary: "Say exactly what you mean — in emails, reports, pitches, and feedback — with AI as your editor.",
    learningObjectives: ["Write clear, precise communications", "Use AI to eliminate vagueness", "Practice concise professional writing"],
    difficulty: "intermediate",
    estimatedMinutes: 25,
    instructorId: "claire",
    trackSlug: "creative-ai",
    order: 5,
    labConnection: "Prompt Lab — precision writing drills",
    projectConnection: "Rewrite 5 pieces of your own writing to be 50% shorter and clearer",
    reflectionPrompt: "When has vague communication caused a real problem in your life?",
  },
  {
    title: "Voice and Tone in AI-Assisted Work",
    slug: "voice-tone-ai-work",
    summary: "AI can match any voice — but first you need to know your own. Discover and calibrate your writing identity.",
    learningObjectives: ["Define your writing voice", "Train AI to match your tone", "Detect and fix voice inconsistencies"],
    difficulty: "intermediate",
    estimatedMinutes: 25,
    instructorId: "claire",
    trackSlug: "creative-ai",
    order: 6,
    labConnection: "Prompt Lab — voice training session",
    projectConnection: "Create a voice guide that AI can follow for all your future work",
    reflectionPrompt: "If AI can sound like anyone, what makes your voice worth keeping?",
  },
];

// ─── CAMERON FRYE — 5 lessons ───────────────────────────────────

const cameron: LessonStub[] = [
  {
    title: "AI Safety for Normal People",
    slug: "ai-safety-normal-people",
    summary: "You don't need to be an expert to be safe. Practical safety habits anyone can follow.",
    learningObjectives: ["Identify 5 everyday AI risks", "Build a personal safety checklist", "Know when to stop and think"],
    difficulty: "beginner",
    estimatedMinutes: 20,
    instructorId: "cameron",
    trackSlug: "ai-foundations",
    order: 8,
    labConnection: "Prompt Lab — safety scenario testing",
    projectConnection: "Create a family-friendly AI safety guide",
    reflectionPrompt: "What's the one AI risk that worries you most? Is that worry justified?",
  },
  {
    title: "Risk Checks Before You Trust Output",
    slug: "risk-checks-before-trust",
    summary: "A 5-step checklist to evaluate AI output before you act on it — prevent bad decisions.",
    learningObjectives: ["Apply the 5-step trust checklist", "Score AI output reliability", "Practice 'trust but verify'"],
    difficulty: "beginner",
    estimatedMinutes: 20,
    instructorId: "cameron",
    trackSlug: "ai-foundations",
    order: 9,
    labConnection: "Prompt Lab — output verification exercise",
    projectConnection: "Use the checklist on 10 real AI outputs and document results",
    reflectionPrompt: "When is it OK to trust AI output without checking? Is it ever?",
  },
  {
    title: "Overreliance Problems — When AI Makes You Lazy",
    slug: "overreliance-problems",
    summary: "The more you rely on AI, the less you practice thinking. Learn to maintain your edge.",
    learningObjectives: ["Identify overreliance patterns", "Design AI-free practice sessions", "Balance AI use with skill building"],
    difficulty: "intermediate",
    estimatedMinutes: 25,
    instructorId: "cameron",
    trackSlug: "ethics-society",
    order: 6,
    labConnection: "All Labs — do one task AI-free, one with AI, compare",
    projectConnection: "Write a personal 'AI Dependency Audit' and action plan",
    reflectionPrompt: "What skill are you losing because AI does it for you?",
  },
  {
    title: "Human Oversight — Why It Still Matters",
    slug: "human-oversight",
    summary: "AI automates, but humans decide. Learn the critical role of human judgment in AI systems.",
    learningObjectives: ["Explain human-in-the-loop systems", "Identify oversight failure cases", "Design oversight protocols"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "cameron",
    trackSlug: "ethics-society",
    order: 7,
    labConnection: "Agent Lab — add human checkpoints to an agent workflow",
    projectConnection: "Design an oversight protocol for a real AI deployment scenario",
    reflectionPrompt: "If an AI makes a mistake, who is responsible — the AI, the builder, or the user?",
  },
  {
    title: "Safe Deployment Practices",
    slug: "safe-deployment-practices",
    summary: "Before you ship AI, run these checks. A deployment safety playbook for responsible builders.",
    learningObjectives: ["Create a pre-deployment checklist", "Run safety tests on AI output", "Document risk mitigation"],
    difficulty: "advanced",
    estimatedMinutes: 35,
    instructorId: "cameron",
    trackSlug: "agent-frameworks",
    order: 4,
    labConnection: "Code Lab — deployment safety exercise",
    projectConnection: "Create a Safety Certification doc for one of your projects",
    reflectionPrompt: "What would it take for you to trust an AI system with something important?",
  },
];

// ─── ZACK MORRIS — 5 lessons ────────────────────────────────────

const zack: LessonStub[] = [
  {
    title: "Product Positioning with AI",
    slug: "product-positioning-ai",
    summary: "How to position a product so the right people find it, understand it, and want it — with AI as your strategist.",
    learningObjectives: ["Write a positioning statement", "Use AI for competitive analysis", "Test messaging with AI feedback"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "zack",
    trackSlug: "ai-business",
    order: 6,
    labConnection: "Project Studio — positioning workshop",
    projectConnection: "Write 3 positioning statements for a real or fictional product",
    reflectionPrompt: "What's the difference between what your product does and why someone needs it?",
  },
  {
    title: "User Attention — How to Earn It",
    slug: "user-attention-earn-it",
    summary: "Attention is the most scarce resource. Learn ethical strategies to earn and keep it with AI tools.",
    learningObjectives: ["Map attention competition", "Design engagement hooks", "Distinguish ethical from manipulative attention tactics"],
    difficulty: "intermediate",
    estimatedMinutes: 25,
    instructorId: "zack",
    trackSlug: "ai-business",
    order: 7,
    labConnection: "Media Lab — attention economy analysis",
    projectConnection: "Design an ethical engagement strategy for one product",
    reflectionPrompt: "When does capturing attention become manipulation?",
  },
  {
    title: "Growth Loops and AI Automation",
    slug: "growth-loops-ai",
    summary: "Design systems where output creates more input — sustainable growth powered by AI.",
    learningObjectives: ["Identify growth loop patterns", "Design one AI-automated growth loop", "Measure loop effectiveness"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "zack",
    trackSlug: "ai-business",
    order: 8,
    labConnection: "Project Studio — growth loop design",
    projectConnection: "Implement a growth loop for your project",
    reflectionPrompt: "What's the simplest growth loop you've ever seen? Why did it work?",
  },
  {
    title: "Practical Leverage Systems",
    slug: "practical-leverage-systems",
    summary: "Do more with less — identify where AI multiplies your effort and build systems around it.",
    learningObjectives: ["Audit personal leverage points", "Build 3 AI force multipliers", "Track ROI of AI automation"],
    difficulty: "beginner",
    estimatedMinutes: 25,
    instructorId: "zack",
    trackSlug: "ai-business",
    order: 9,
    labConnection: "Prompt Lab + Code Lab — leverage system build",
    projectConnection: "Document your top 5 AI leverage points with time savings",
    reflectionPrompt: "Where in your life does effort NOT scale? Can AI change that?",
  },
  {
    title: "Launch Your First AI-Powered Thing",
    slug: "launch-first-ai-thing",
    summary: "Time out! Stop planning. Start building. This lesson walks you through a real launch.",
    learningObjectives: ["Choose a launch candidate", "Set up in 60 minutes", "Ship to at least 3 real users"],
    difficulty: "intermediate",
    estimatedMinutes: 45,
    instructorId: "zack",
    trackSlug: "ai-business",
    order: 10,
    labConnection: "Project Studio — launch day simulation",
    projectConnection: "Actually launch something and collect user feedback",
    reflectionPrompt: "What held you back from launching sooner? Was it a real blocker or just fear?",
  },
];

// ─── LISA TURTLE — 5 lessons ────────────────────────────────────

const lisa: LessonStub[] = [
  {
    title: "Design Taste in the AI Era",
    slug: "design-taste-ai-era",
    summary: "AI can generate anything. Taste decides what's worth keeping. Learn to curate, not just create.",
    learningObjectives: ["Define design taste", "Evaluate AI-generated designs", "Build a taste portfolio"],
    difficulty: "beginner",
    estimatedMinutes: 25,
    instructorId: "lisa",
    trackSlug: "creative-ai",
    order: 7,
    labConnection: "Media Lab — design taste exercise",
    projectConnection: "Curate a 'Best of AI' design collection with commentary",
    reflectionPrompt: "Can taste be learned, or is it innate? How has your taste changed?",
  },
  {
    title: "Cultural Trend Analysis with AI",
    slug: "cultural-trend-analysis",
    summary: "Use AI to spot, track, and predict cultural trends — from fashion to technology to language.",
    learningObjectives: ["Identify emerging trends", "Use AI for trend analysis", "Create a trend report"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "lisa",
    trackSlug: "creative-ai",
    order: 8,
    labConnection: "Media Lab — trend detection exercise",
    projectConnection: "Publish a '5 Trends AI Sees Coming' report",
    reflectionPrompt: "What trend did you miss that AI might have caught?",
  },
  {
    title: "Visual Identity and AI Tools",
    slug: "visual-identity-ai-tools",
    summary: "Build a visual brand that's consistent, recognizable, and authentically yours — with AI assistance.",
    learningObjectives: ["Define visual identity principles", "Generate brand assets with AI", "Maintain consistency across platforms"],
    difficulty: "intermediate",
    estimatedMinutes: 30,
    instructorId: "lisa",
    trackSlug: "creative-ai",
    order: 9,
    labConnection: "Media Lab — visual identity workshop",
    projectConnection: "Create a complete visual identity kit for a personal brand",
    reflectionPrompt: "Does having AI-generated visuals make your brand less authentic?",
  },
  {
    title: "AI + Fashion / Brand / Media",
    slug: "ai-fashion-brand-media",
    summary: "How AI is transforming creative industries — and how you can participate, not just consume.",
    learningObjectives: ["Map AI's impact on creative industries", "Identify creator opportunities", "Build a creative AI portfolio"],
    difficulty: "intermediate",
    estimatedMinutes: 25,
    instructorId: "lisa",
    trackSlug: "creative-ai",
    order: 10,
    labConnection: "Media Lab — industry disruption analysis",
    projectConnection: "Create one piece of AI-assisted creative content for a real audience",
    reflectionPrompt: "If AI can create art, what is the value of human creativity?",
  },
  {
    title: "Reading Culture Through Data",
    slug: "reading-culture-data",
    summary: "Culture leaves data trails. Learn to read them — music trends, language shifts, visual patterns.",
    learningObjectives: ["Identify cultural data sources", "Use AI for cultural pattern analysis", "Create a cultural data visualization"],
    difficulty: "advanced",
    estimatedMinutes: 35,
    instructorId: "lisa",
    trackSlug: "creative-ai",
    order: 11,
    labConnection: "Media Lab — cultural data analysis",
    projectConnection: "Build a data-driven cultural analysis of one topic you care about",
    reflectionPrompt: "What does the data say about your generation that surprises you?",
  },
];

// ─── ALL LESSONS COMBINED ───────────────────────────────────────

export const allLessonStubs: readonly LessonStub[] = [
  ...spicoli,
  ...miyagi,
  ...brian,
  ...dwayne,
  ...ferris,
  ...bender,
  ...claire,
  ...cameron,
  ...zack,
  ...lisa,
] as const;

/**
 * Get lessons for a specific instructor
 */
export function getLessonsByInstructor(instructorId: string): readonly LessonStub[] {
  return allLessonStubs.filter((l) => l.instructorId === instructorId);
}

/**
 * Get lessons for a specific track
 */
export function getLessonsByTrack(trackSlug: string): readonly LessonStub[] {
  return allLessonStubs.filter((l) => l.trackSlug === trackSlug);
}

/**
 * Instructor → Track mapping summary
 */
export const instructorTrackMap = {
  spicoli: ["ai-foundations", "prompt-engineering", "creative-ai"],
  miyagi: ["ai-foundations"],
  brian: ["rag-search"],
  dwayne: ["mcp-tools", "agent-frameworks"],
  ferris: ["ai-business"],
  bender: ["ethics-society"],
  claire: ["creative-ai"],
  cameron: ["ai-foundations", "ethics-society", "agent-frameworks"],
  zack: ["ai-business"],
  lisa: ["creative-ai"],
} as const;
